version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: yvk09/food_backend
    restart: unless-stopped

    volumes:
     - static_value:/app/static/
     - media_value:/app/media/
    depends_on:
     - db
    env_file:
     - ./.env

  frontend:
    image: yvk09/food_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
     - db

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - backend
      - frontend

volumes:
  data_value:
  static_value:
  media_value: