# Generated by Django 3.2.2 on 2023-08-23 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230823_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение: 1'), django.core.validators.MaxValueValidator(9999, 'Максимальное значение: 9999'), django.core.validators.RegexValidator('^[0-9]+$', 'Количество ингредиента может быть целым числом от 1 до 9999')], verbose_name='Количество ингредиента в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше "1"')], verbose_name='Время приготовления'),
        ),
    ]
