# Generated by Django 3.2.2 on 2023-08-25 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название тега, только русские буквы.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Проверьте вводимый формат', regex='[а-яА-Я]')], verbose_name='Название тега'),
        ),
    ]
