# Generated by Django 3.2.2 on 2023-09-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
    ]
